name: build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '10.0.x'

jobs:
  build:
    name: Build and Tag
    runs-on: windows-latest
    # Map the step outputs to job outputs so the next job can see them
    outputs:
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Install dependencies
        run: dotnet restore
        
      - name: Install Packages
        run: |
          dotnet add package Newtonsoft.Json --version 13.0.4
          dotnet add package SnmpSharpNet --version 0.9.7
          
      - name: Build
        run: dotnet publish -r win-x64 -p:PublishSingleFile=true --self-contained true
        
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Raw Binary
        uses: actions/upload-artifact@v4
        with:
          name: compiled-exe
          path: bin/Release/net10.0-windows10.0.26100.0/win-x64/publish/
          retention-days: 1

  sign_and_release:
    name: Sign and Release
    needs: build
    runs-on: windows-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: compiled-exe
          path: out/

      - name: Rename EXE with Version
        # We access the version via the 'needs' context
        run: |
          mv out\PrinterAddV2.exe out\PrinterAddV2_${{ needs.build.outputs.new_tag }}.exe -Force

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Sign files
        uses: azure/artifact-signing-action@v1
        with:
          endpoint: https://weu.codesigning.azure.net/
          signing-account-name: m2s-signing
          certificate-profile-name: M2SPrimary
          files-folder: out/
          files-folder-filter: exe,dll
          file-digest: SHA256
          timestamp-rfc3161: http://timestamp.acs.microsoft.com
          timestamp-digest: SHA256      
      - name: Zip Files
        uses: vimtor/action-zip@v1.2
        with:
          files: out/
          dest: out/PrinterAddV2_${{ needs.build.outputs.new_tag }}.zip
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: out/*
          tag_name: ${{ needs.build.outputs.new_tag }}
          name: Release ${{ needs.build.outputs.new_tag }}
          body: ${{ needs.build.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  changelog:
    name: Create and Commit Changelog
    needs: sign_and_release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Generate Changelog
      uses: MACH-2-Simulations/changelog_nochores@2.0.0
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Git User Info
      run: |
        git config user.name 'GitHub Actions Bot'
        git config user.email 'actions@github.com'

    - name: Commit Changelog
      run: |
        git add 'CHANGELOG.md'
        git commit -m "chore: :robot: changelog file generated" || echo "No changes to commit"
        git push
